# only for development
version: '3'

volumes:
  database:
  bundle:

services:
  app:
    env_file: .env
    build: &build
      context: ../../
      dockerfile: devops/dev/Dockerfile
    image: sshkarupa/app:dev
    volumes: &volumes
      - ../../:/usr/src/app
      - bundle:/usr/local/bundle
    command: bin/rails s -b 0.0.0.0
    ports:
      - 3000:3000
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:11-alpine
    volumes:
      - database:/var/lib/postgresql/data

  # NOTE: only if you're going to use webpacker gem
  webpacker:
    build: *build
    image: sshkarupa/app:dev
    volumes: *volumes
    command: bin/webpack-dev-server
    ports:
      - 3035:3035
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
